### ISSUE TITLE
🛠️ Add modern development tools and code quality standards

### ISSUE THREAD

**Issue by kjarisk** [kjarisk/fisherman-adventure#5]
### Current State
The project lacks modern development tooling and code quality standards that are considered essential for React projects in 2025.

#### Code Quality & Linting:
- **ESLint configuration**: No custom linting rules
- **Prettier**: No code formatting standards
- **TypeScript**: Consider migration for better type safety
- **Husky**: Pre-commit hooks for code quality

#### Testing Infrastructure:
- **Jest setup**: Improve test configuration  
- **React Testing Library**: Component testing utilities
- **Coverage reporting**: Track test coverage
- **E2E testing**: Consider Cypress or Playwright for game testing

#### Build & Deployment:
- **GitHub Actions**: Automated CI/CD pipeline
- **Build optimization**: Bundle analysis and optimization
- **Deploy previews**: Automatic deployment for PRs
- **Performance monitoring**: Bundle size tracking

#### Developer Experience:
- **VS Code settings**: Workspace configuration
- **EditorConfig**: Consistent formatting across editors
- **Import sorting**: Automatic import organization
- **Path mapping**: Absolute imports from src

#### 1. ESLint + Prettier Setup:
```json
// .eslintrc.js
{
  "extends": [
    "react-app",
    "react-app/jest",
    "prettier"
  ],
  "rules": {
    "no-console": "warn",
    "react-hooks/exhaustive-deps": "error"
  }
}
```

#### 2. Package.json Scripts:
```json
{
  "scripts": {
    "lint": "eslint src --ext .js,.jsx",
    "lint:fix": "eslint src --ext .js,.jsx --fix",
    "format": "prettier --write src/**/*.{js,jsx,css,md}",
    "test:coverage": "npm test -- --coverage --watchAll=false"
  }
}
```

#### 3. GitHub Actions Workflow:
```yaml
# .github/workflows/ci.yml
name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --coverage --watchAll=false
      - name: Build
        run: npm run build
```

#### 4. Pre-commit Hooks:
```json
// package.json
{
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "src/**/*.{js,jsx}": [
      "eslint --fix",
      "prettier --write"
    ]
  }
}
```

### Benefits:
- **Code Quality**: Consistent code style and catch errors early
- **Developer Productivity**: Automated formatting and linting
- **Reliability**: Automated testing and CI/CD
- **Maintainability**: Better code organization and standards
- **Collaboration**: Clear coding standards for contributors

### Implementation Priority:
1. **High Priority**: ESLint + Prettier (immediate code quality)
2. **Medium Priority**: GitHub Actions CI (automated testing)
3. **Low Priority**: TypeScript migration (future enhancement)

### Effort Estimates:
- ESLint/Prettier setup: 1-2 hours
- GitHub Actions: 1 hour  
- Pre-commit hooks: 30 minutes
- VS Code workspace: 15 minutes

### Dependencies to Add:
```bash
npm install --save-dev eslint-config-prettier prettier husky lint-staged
```

### Tags: `tooling`, `developer-experience`, `code-quality`, `phi4`
